apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: anand-rs
  labels:
    app: my-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-helloworld
  template:
    metadata:
      labels:
        app: my-helloworld
    spec:
      containers:
      - name: myenginexpod1
        image: nginx
